//rpccal///
struct number {
    float a;
    float b;
};

typedef float result;

program CAL_PROG {
    version CAL_VERS {
        result ADD(number) = 1;
        result SUB(number) = 2;
        result MUL(number) = 3;
        result DIV(number) = 4;
    } = 1;
} = 0x12345678;

////////client/////
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"
#include<stdio.h>
#include <stdlib.h>

void
cal_prog_1(char *host)
{
	CLIENT *clnt;
	result  *result_1;
	number  add_1_arg;
	result  *result_2;
	number  sub_1_arg;
	result  *result_3;
	number  mul_1_arg;
	result  *result_4;
	number  div_1_arg;
	
	float num1,num2;
	char op;

#ifndef	DEBUG
	clnt = clnt_create (host, CAL_PROG, CAL_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

    printf("Enter the numbers with paremeter");
    scanf("%f %c %f",&num1,&op,&num2);

	if(op=='+') {
    add_1_arg.a=num1;
	add_1_arg.b=num2;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
        printf("Answer is %f",*result_1);
	}

	else 

	  if (op=='-') {
		sub_1_arg.a=num1;
		sub_1_arg.b=num2;
      result_2 = sub_1(&sub_1_arg, clnt);
	  if (result_2 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	  printf("Answer is %f",*result_2);

	  }

	  else

	      if (op=='*') {
		mul_1_arg.a=num1;
		mul_1_arg.b=num2;	
	    result_3 = mul_1(&mul_1_arg, clnt);
	    if (result_3 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Answer is %f",*result_3);

		  }

		  else
		     if (op=='/') {
	div_1_arg.a=num1;
	div_1_arg.b=num2;			
    result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (result *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    printf("Answer is %f",*result_4);
			 }

else {
	printf("Invalid");
}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cal_prog_1 (host);
exit (0);
}

/////server///

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cal.h"

result *
add_1_svc(number *argp, struct svc_req *rqstp)
{
	static result  result;

	result= argp->a  + argp->b; 

	return &result;
}

result *
sub_1_svc(number *argp, struct svc_req *rqstp)
{
	static result  result;

	result= argp->a  - argp->b;

	return &result;
}

result *
mul_1_svc(number *argp, struct svc_req *rqstp)
{
	static result  result;

	result= argp->a  *  argp->b;

	return &result;
}

result *
div_1_svc(number *argp, struct svc_req *rqstp)
{
	static result  result;

result= argp->a  / argp->b;
	return &result;
}

///////max process mpi////
#include <mpi.h>
#include <stdio.h>
#include <string.h>

int main (int argc,char *argv[]) {
    int rank,size;
    char message[100];

  MPI_Init(&argc,&argv);

  MPI_Comm_rank(MPI_COMM_WORLD,&rank);
  MPI_Comm_size(MPI_COMM_WORLD,&size);

  //check minimum number of process
  if(size < 2) {
    if(rank == 0) {
        printf("This program requires at least 2 process.\n");

    }
        MPI_Finalize();
        return 0;

  }

  if (rank == 0) {
    strcpy(message,"Hellow from process 0");
    MPI_Send(message,strlen(message)+1,MPI_CHAR,1,0,MPI_COMM_WORLD);
    printf("Process 0 sent message:%s\n",message);
  }

  else if (rank == 1) {
    MPI_Recv(message,100,MPI_CHAR,0,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
    printf("Process 1 received message:%s\n",message);
  }
    MPI_Finalize();
    return 0;
}

////max value///
#include <mpi.h>
#include <stdio.h>
int main(int argc,char *argv[]){
    int rank,size;
    int number[5];
    int max,i;

    MPI_Init(&argc,&argv);

    MPI_Comm_rank(MPI_COMM_WORLD,&rank);
    MPI_Comm_size(MPI_COMM_WORLD,&size);

    if (size < 2) {
        if(rank==0) {
            printf("use must be atleast 2 process");
        }
        MPI_Finalize();
        return 0;
    }
  if(rank==0) {
    printf("Enter the five number:\n");
    for(i=0;i<5;i++) {
            scanf("%d",&number[i]);
        }

        MPI_Send(number,5,MPI_INT,1,0,MPI_COMM_WORLD);
    }
    else if (rank == 1) {
        MPI_Recv(number,5,MPI_INT,0,0,MPI_COMM_WORLD,MPI_STATUS_IGNORE);
       max = number[0];
       for(i=1;i<5;i++) {
        if (number[i] > max)
        max = number[i];
       }

       printf("Maximum value = %d\n",max);
    }

    MPI_Finalize();
    return 0;
  }

///student result rpc//

---result.x---

struct student_input{
  string name<50>;
  int regno;
  int marks[5];
};

struct student_result{
    int total;
    int avg;
    char grade;

};

program MARKS_PROG{
    version MARKS_VERS{

        student_result CAL_RESULT(student_input) = 1;

    }=1;
} = 0x23456789;

---server----
/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "result.h"

student_result *
cal_result_1_svc(student_input *argp, struct svc_req *rqstp)
{
	static student_result  result;
    int i;

	result.total = 0;
	for(i=0;i<5;i++) {
		result.total += argp->marks[i];
	}

	result.avg = result.total/5.0;

	if(result.avg >= 75)
	result.grade = 'A';
else if (result.avg >= 65)
    result.grade = 'B';
else if (result.avg>=55)
    result.grade = 'C';
else if (result.avg >=40)
    result.grade = 'F';

	return &result;
}

----result client---

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include "result.h"


void
marks_prog_1(char *host)
{
	CLIENT *clnt;
	student_result  *result_1;
	student_input  cal_result_1_arg;
	int i;

#ifndef	DEBUG
	clnt = clnt_create (host, MARKS_PROG, MARKS_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

   //inputs take

   printf("Enter the Student name:");
   scanf ("%s",cal_result_1_arg.name);

   printf("Enter the student register number:");
   scanf ("%d",&cal_result_1_arg.regno);

   printf("Enter the 5 subject marks:\n");
   for (i = 0;i<5;i++) {
   scanf ("%d",&cal_result_1_arg.marks[i]);
   }
 

	result_1 = cal_result_1(&cal_result_1_arg, clnt);
	if (result_1 == (student_result *) NULL) {
		clnt_perror (clnt, "call failed");
		exit(1);
	}

   printf("\n--------Student Result--------");
   printf("Total:%d\n",result_1->total);
   printf("Avg:%d\n",result_1->avg);
   printf("Grade:%c\n",result_1->grade);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	marks_prog_1 (host);
exit (0);
}


